name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
    - name: Increment Build Number
      run: |
      cd gotg-lib
      sh increment_build_number.sh

  build-site:
    runs-on: ubuntu-latest
    needs: increment-version
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build Site
      run: |
        cd gotg-client
        sh build.sh
    - name: Deploy Site
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: gotg-client/build
       
