name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build Wasm
      run: wasm-pack build --target web
    - name: Deploy Site
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: pkg
       
